package agent

import "gopkg.in/mgo.v2/bson"

type AgentStatus string

const CollectionName = "agents"

const (
	Registered AgentStatus = "waiting" // Agent created, but doesn't approved
	Approved               = "approved"
)

type Agent struct {
	Id       bson.ObjectId `json:"id" bson:"_id"`           // autogenerated id
	Approved bool          `json:"approved"`                // Agent created, but aren't approved
	Name     string        `json:"name" binding:"required"` // is usually a hostname
	//	Status

}

func New() *Agent {
	return &Agent{}
}
