package agent

import (
	"gopkg.in/mgo.v2/bson"
	"encoding/json"
)

type AgentStatus string

// It's a hack to show custom type as string in swagger
func (t AgentStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(t))
}

const CollectionName = "agents"

const (
	Registered AgentStatus = "waiting" // Agent created, but doesn't approved
	Approved               = "approved"
)

type Agent struct {
	Id       bson.ObjectId `json:"id" bson:"_id"`           // autogenerated id
	Approved bool          `json:"approved"`                // Agent created, but aren't approved
	Name     string        `json:"name" binding:"required"` // is usually a hostname
	//	Status

}

func New() *Agent {
	return &Agent{}
}
