// generated by stringer -type=Cmd; DO NOT EDIT

package message

import "fmt"

const _Cmd_name = "CmdReponseCmdErrorCmdGetPluginVersionsCmdRunPlugin"

var _Cmd_index = [...]uint8{0, 10, 18, 38, 50}

func (i Cmd) String() string {
	if i < 0 || i+1 >= Cmd(len(_Cmd_index)) {
		return fmt.Sprintf("Cmd(%d)", i)
	}
	return _Cmd_name[_Cmd_index[i]:_Cmd_index[i+1]]
}
